cvm-version: 0.7.1
cpus: 16
memory: 65536

containers:
  - name: "garden-app"
    image: "us-central1-docker.pkg.dev/workshop-labs-pbc/garden-docker/app@sha256:160e3a287e26a48a510f348bb1154ba4e9cd153b9ce042763a87aae3bd50f566"
    volumes:
      - /mnt/ramdisk/gcloud_key.json:/key.json:ro
    env:
      - NODE_ENV: "production"
      - NODE_OPTIONS: "--max-old-space-size=28672"
      - GOOGLE_APPLICATION_CREDENTIALS: "/key.json"
      - GCS_BUCKET: "pollux-enc-prod"
      - POLLUX_LN_GCS_BUCKET: "gs://pollux-enc-prod"
      - SYNC_SERVER_URL: "https://pollux-sync.debug.wsl.containers.tinfoil.dev"
      - EMBEDDING_SERVER_URL: "https://confidential-pollux-embeddings.debug.wsl.containers.tinfoil.dev"
      - TRAINING_SERVER_URL: "https://training.debug.wsl.containers.tinfoil.dev"
      - MEMEX_SERVER_URL: "https://memex.debug.wsl.containers.tinfoil.dev"
      - DEBUG_ARTEFACT_CHAT: "true"
      - EMAIL_VERIFY_ENABLED: "false"
      - INFERENCE_SERVER_URL: "https://inference.debug.wsl.containers.tinfoil.dev/v1"
    secrets:
      - DATABASE_URL
      - BETTER_AUTH_SECRET
      - RESEND_API_KEY
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - EXA_API_KEY
      - TINFOIL_API_KEY
      - TINFOIL_API_KEY_BACKUP_ACCOUNT
      - INTERNAL_SERVICE_SECRET

shim:
  upstream-port: 3000
  tls-challenge: http
